//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base("name=QLNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblNCC> tblNCCs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblNXB> tblNXBs { get; set; }
        public virtual DbSet<tblPhieuNhap> tblPhieuNhaps { get; set; }
        public virtual DbSet<tblPhieuXuat> tblPhieuXuats { get; set; }
        public virtual DbSet<tblSach> tblSaches { get; set; }
        public virtual DbSet<tblTacGia> tblTacGias { get; set; }
        public virtual DbSet<tblTheLoai> tblTheLoais { get; set; }
        public virtual DbSet<tblCTPhieuNhap> tblCTPhieuNhaps { get; set; }
        public virtual DbSet<tblCTPhieuXuat> tblCTPhieuXuats { get; set; }
    }
}
