//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuXuat
    {
        public int ma_px { get; set; }
        public Nullable<int> ma_nv { get; set; }
        public Nullable<int> ma_kh { get; set; }
        public Nullable<System.DateTime> ngay_xuat { get; set; }
    
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblCTPhieuXuat tblCTPhieuXuat { get; set; }
    }
}
